// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace elbgb_test
{
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ResultTable : ResultTableBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!DOCTYPE html>
<html>
<head>
	<title>elbgb_test results</title>
    <style>
        body { margin: 20px; font-family:Arial,Sans-Serif; }
		
		h1 { padding-bottom:20px; margin-bottom:20px; border-bottom:1px solid silver; }
		
		.summary { border:1px solid silver; margin-bottom:20px; text-align:center; }
		
		.summary .passing { background-color:lime; color:black; }
		.summary .failing { background-color:red; color:white; }
		
        .results { width:100%; border-collapse:collapse; }
        .results, .results th, .results td { border:1px solid silver; }

		.results th { height:50px; }
		.results td { text-align:center; padding:5px; }
		.results td.name { text-align:left; }
        .results .passing { color:green; }
        .results .failing { color:red; }

        .duration { font-size:8pt; color:silver; }
    </style>
</head>
<body>
    <h1>elbgb_test results</h1>
    <div class=""summary"">
        <p>Executed ");
            
            #line 36 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_testResults.Count));
            
            #line default
            #line hidden
            this.Write(" tests in ");
            
            #line 36 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_duration.TotalSeconds));
            
            #line default
            #line hidden
            this.Write(" seconds.</p>\r\n    </div>\r\n");
            
            #line 38 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"

    List<Test> inconclusive = _testResults.Where(x => x.Result == TestStatus.Inconclusive).ToList();

    if (inconclusive.Count > 0)
    {

            
            #line default
            #line hidden
            this.Write("    <h2>Inconclusive</h2>\r\n    <table class=\"results\">\r\n\t\t<tr>\r\n\t\t\t<th>Image</th>" +
                    "\r\n\t\t\t<th>Test</th>\r\n\t\t\t<th>Result</th>\r\n\t\t\t<th>Hash</th>\r\n\t\t</tr>\r\n");
            
            #line 52 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
      foreach (var test in inconclusive)
        { 
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n\t\t\t<td><img src=\"");
            
            #line 55 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path.ChangeExtension(test.Name, "png")));
            
            #line default
            #line hidden
            this.Write("\"</td>\r\n\t\t\t<td class=\"name\">");
            
            #line 56 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Name));
            
            #line default
            #line hidden
            this.Write(" <span class=\"duration\">");
            
            #line 56 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Duration));
            
            #line default
            #line hidden
            this.Write("ms</span></td>\r\n\t\t\t<td class=\"");
            
            #line 57 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Result.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 57 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Result));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t<td class=\"hash\">");
            
            #line 58 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Hash));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t</tr>\r\n");
            
            #line 60 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
      } 
            
            #line default
            #line hidden
            this.Write("\t</table>\r\n");
            
            #line 62 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n    <h2>Failing/Passing</h2>\r\n\t<table class=\"results\">\r\n\t\t<tr>\r\n\t\t\t<th>Image</t" +
                    "h>\r\n\t\t\t<th>Test</th>\r\n\t\t\t<th>Result</th>\r\n\t\t\t<th>Hash</th>\r\n\t\t</tr>\r\n");
            
            #line 72 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
  foreach (var test in _testResults.Where(x => x.Result != TestStatus.Inconclusive).OrderBy(x => x.Result))
    { 
            
            #line default
            #line hidden
            this.Write("\t\t<tr>\r\n\t\t\t<td><img src=\"");
            
            #line 75 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Path.ChangeExtension(test.Name, "png")));
            
            #line default
            #line hidden
            this.Write("\"</td>\r\n\t\t\t<td class=\"name\">");
            
            #line 76 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Name));
            
            #line default
            #line hidden
            this.Write(" <span class=\"duration\">");
            
            #line 76 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Duration));
            
            #line default
            #line hidden
            this.Write("ms</span></td>\r\n\t\t\t<td class=\"");
            
            #line 77 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Result.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 77 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Result));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t<td class=\"hash\">");
            
            #line 78 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(test.Hash));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t</tr>\r\n");
            
            #line 80 "E:\projects\elbgb2\elbgb_test\ResultTable.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\t</table>\r\n</body>\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class ResultTableBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
